config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :transactions, only: %w[new create show]

  namespace :admin do
    resources :transactions, only: :index
  end

  root to: 'transactions#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  MINE_FEE = 0.000006

  scope :success, -> { where.not(tx_id: nil) }

  def btc_value
    v = Tx::CalculateTotalValues.new(usdt_value, exchange_rate).call
    v.btc_value
  end

  def status
    return 'success' if tx_id.present?

    'fail'
  end
end

app/controllers/admin/transactions_controller.rb
# frozen_string_literal: true

module Admin
  class TransactionsController < AdminBaseController
    def index
      @txs = Transaction.order(:created_at)
      @successful_tx_count = @txs.success.count
      @total_exchange_fee = @txs.sum(:exchange_fee)
    end
  end
end

app/controllers/admin_base_controller.rb
# frozen_string_literal: true

class AdminBaseController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'password'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  def new
    @tx = Transaction.new
    @errors = {}
  end

  def create
    mutator.build

    if mutator.errors.present?
      @errors = mutator.errors
      @tx = mutator.object

      render :new
    else
      redirect_to transaction_path(@mutator.object.id)
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
    @mine_fee = Transaction::MINE_FEE
  end

  private

  def mutator
    @mutator ||= TransactionMutator.new(tx_params)
  end

  def tx_params
    params.require(:transaction).permit(:usdt_value, :exchange_rate, :address, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/transactions/index.html.slim
.admin-wrapper
  h2 Statistics
  table
    tr
      th Total exchange fee
      th Total transactions
      th Total success transactions
    tr
      td = "#{@total_exchange_fee} tBTC"
      td = @txs.count
      td = @successful_tx_count

  h2 Transactions
  table
    tr
      th id
      th data/time
      th e-mail
      th txid
      th to
      th exchange rate
      th exchange fee
      th status
    - @txs.each do |tx|
      tr
        td = tx.id
        td = tx.created_at.strftime('%D %R')
        td = tx.email
        td = tx.tx_id
        td = tx.address
        td = tx.exchange_rate
        td = "#{tx.exchange_fee} tBTC"
        td = tx.status

app/views/layouts/application.html.slim
doctype html
html
  head
    title Demo exchanger
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/transactions/new.html.slim
.main
  .wrapper data-controller="transaction"
    h2.m-bottom-24 Calculate amount
    = form_for @tx do |f|
      = f.hidden_field :exchange_rate, data: { 'transaction-target' => 'exchangeRate' }

      .m-bottom-24
        = f.label 'You sent', class: 'label'
        .field-wrapper
          = f.number_field :usdt_value, step: 0.01, class: @errors[:usdt_value].present? ? 'field field--error' : 'field',
            data: { 'transaction-target' => 'usdtInput', action: 'input->transaction#input' }
          .field-wrapper__units.small USDT
        .error = @errors[:usdt_value].try(:first)

      .row.row--align-between.row--height-15.m-bottom-24
        .column.column--align-center
          = image_tag 'loader.svg', height: '15px', data: { 'transaction-target' => 'loader' }
          .small.hidden data-transaction-target="rate"
        .column.column--align-center
          = image_tag 'exchange.svg', height: '15px'

      .m-bottom-24
        = f.label 'You get', class: 'label'
        .field-wrapper
          input name='btc_value' readonly="true" class='field' data-transaction-target='btcInput'
          .field-wrapper__units.small tBTC

      h2.m-bottom-24 Wallet address
      .m-bottom-12
        = f.label 'Recepient address', class: 'label'
        = f.text_field :address, class: @errors[:address].present? ? 'field field--error' : 'field'
        .error = @errors[:address].try(:first)

      .m-bottom-12
        = f.label 'Email', class: 'label'
        = f.email_field :email, class: @errors[:email].present? ? 'field field--error' : 'field'
        .error = @errors[:email].try(:first)

      .m-bottom-24
        .checkbox
          input id="policy" type='checkbox' name='policy' data-action='change->transaction#check' data-transaction-target='checkbox'
          label for='policy' I agree with terms of use

      = f.submit 'Exchange now', disabled: true, class: 'button button--disabled', data: { 'transaction-target' => 'submit' }

app/views/transactions/show.html.slim
.main
  .wrapper.wrapper--big
    .row.row--align-between.m-bottom-30
      .column.column--align-center
        h2 Transaction ##{@transaction.id}
      .column.column--align-center
        = link_to 'Back', new_transaction_path, class: 'link'

    .row.row--align-between.m-bottom-12
      .column.column--vertical
        h3 You sent
        = number_to_currency(@transaction.usdt_value, unit: 'USDT', format: "%n %u")
      .column.column--vertical.right-aligned
        h3 You get
        = number_to_currency(@transaction.btc_value, precision: 12, unit: 'tBTC', format: "%n %u")
    .row.row--align-between.m-bottom-12
      .column.column--vertical
        h3 Exchange fee
        = number_to_currency(@transaction.exchange_fee, precision: 12, unit: 'tBTC', format: "%n %u")
      .column.column--vertical.right-aligned
        h3 Network fee
        = number_to_currency(@mine_fee, precision: 12, unit: 'tBTC', format: "%n %u")
    .row.row--align-between.m-bottom-12
      .column.column--vertical
        h3 Recipient address
        = @transaction.address
    .row.row--align-between.m-bottom-12
      .column.column--vertical
        h3 Email
        = @transaction.email